---
# If possible we use headers from main OS repo for this kernel.
- name: Install Kernel Header and Devel from OS repo for Current Kernel
  yum:
      name:
        - "kernel-headers-{{ hostvars[inventory_hostname].ansible_kernel }}"
        - "kernel-devel-{{ hostvars[inventory_hostname].ansible_kernel }}"

# ensure nouveau being unloaded
- name: Ensure nouveau being unloaded
  modprobe:
    name: nouveau
    state: absent
  changed_when: False

- name: Use Centos Base Repo for vulkan-filesystem
  yum_repository:
    name: vulkanfs-repo
    description: Workaround repo to get vulkan-filesystem
    baseurl: "{{ rhel7_vulkan_repo_baseurl }}"
    gpgkey: "{{ rhel7_vulkan_repo_gpgkey }}"
    enabled: false

- name: Use vulkan-filesystem from centos
  yum:
    name: vulkan-filesystem
    enablerepo: vulkanfs-repo

- name: Install EPEL release
  yum:
    name: "{{ epel_centos_7_rpm }}"
    state: present

# Install NVIDIA repository, driver and tools
- name: Add NVIDIA repository for CUDA drivers and tools
  yum_repository:
    name: cuda
    description: NVIDIA cuda repository
    enabled: true
    baseurl: "{{ nvidia_repo_baseurl }}"
    gpgkey: "{{ nvidia_repo_gpgkey }}"
    gpgcheck: true
- name: Install cuda drivers and tools
  yum:
    enablerepo:
      - rhel-7-server-rhui-extras-rpms
      - rhel-7-server-rhui-optional-rpms
    name:
      - "{{ nvidia_cuda_package }}"
    state: present

# libnvidia-container
- name: Add libnvidia-container repository
  yum_repository:
    name: libnvidia-container
    description: NVIDIA cuda repository
    enabled: false
    baseurl: "{{ libnvidia_container_repo_rhel }}"
    gpgkey: "{{ libnvidia_container_repo_gpgkey }}"
    gpgcheck: true

- name: install libnvidia-container
  yum:
    name: libnvidia-container1
    enablerepo: libnvidia-container
    state: present

- name: Add libnvidia-container-runtime repository
  yum_repository:
    name: nvidia-container-runtime
    description: NVIDIA cuda repository
    enabled: false
    baseurl: "{{ nvidia_container_runtime_repo_rhel }}"
    gpgkey: "{{ nvidia_container_runtime_repo_gpgkey }}"
    gpgcheck: true

- name: Install nvidia-container-tools
  yum:
    name: libnvidia-container-tools
    enablerepo:
      - libnvidia-container
    state: present

- name: Install nvidia-container-runtime
  yum:
    name: "{{ nvidia_container_runtime_package }}"
    enablerepo:
      - nvidia-container-runtime
    state: present
